### ISSUE TITLE
wstan服务端的构造

### ISSUE THREAD

**Issue by xtyxtyx** [krrr/wstan#1]
您好,
我准备用其他语言实现wstan服务端, 请问wstan是如何处理socks与http请求的?
谢谢.

**Comment by krrr** [comment]
socks5和http代理服务端是由wstan的客户端实现的（wstan客户端和wstan服务端通信用的是基于websocket的私有协议）只是实现wstan服务端的话不用关注它们（顺便说下实现在https://github.com/krrr/wstan/blob/master/wstan/client.py#L322 和 https://github.com/krrr/wstan/blob/master/wstan/client.py#L354）

**Comment by krrr** [comment]
能说下你的动机吗，说实话我的协议设计很naive，而且完全没有文档，比起v2ray之类差远了

**Comment by xtyxtyx** [comment]
v2ray还有ss之类的都是tcp直连, 而我所在的网络环境要通过cloudflare反代http才能得到比较稳定的连接效果. 所以可以走http的协议对我来说更重要. 我的打算是先用Dart实现一个wstan服务端, 了解一下具体的实现, 并且可能的话对现有协议进行一些增强. 如果可以的话请告诉我一些wstan私有协议的实现, 感激不尽!

**Comment by krrr** [comment]
赶制了一份简略文档，可能漏了许多东西：https://github.com/krrr/wstan/wiki/Protocol

**Comment by xtyxtyx** [comment]
> There is no multiplexing. Once a request is accepted the tunnel (and underlying TCP conn.) will be  exclusively used by it.

也就是说wstan不存在并发?

还有`SOCKS5 address header`是指下面这部分?
```
field 4: address type, 1 byte:

    0x01 = IPv4 address
    0x03 = Domain name
    0x04 = IPv6 address

field 5: destination address of

    4 bytes for IPv4 address
    1 byte of name length followed by the name for domain name
    16 bytes for IPv6 address

field 6: port number in a network byte order, 2 bytes
```

**Comment by krrr** [comment]
并发当然有，不过不能像http2一样复用tcp连接。ws连接想开多少就开多少

是的，结构和ss的差不多。这里和其他打省略号的地方我稍后补上

**Comment by xtyxtyx** [comment]
`Data message`中有没有HMAC?

**Comment by krrr** [comment]
显然没有。wstan不像SSL，加密和HMAC都是为了防止被gfw检测到而不是安全

ss的设计是客户端往服务端方向始终有HMAC

**Comment by xtyxtyx** [comment]
使用一般方法计算Sec-WebSocket-Accept客户端会报如下错误
> 01-22 15:39:15 E: can't connect to server: HTTP Sec-WebSocket-Accept header missing in opening handshake reply

而写wiki和server.py中都有取前16字节这样的内容
wstan中Sec-WebSocket-Accept具体是怎样计算的?

**Comment by krrr** [comment]
你的ws协议全部手写吗？不然这个field库会帮你计算的。可以直接从`Sec-WebSocket-Accept`取出来。

计算方法
```
base64encode(sha1(base64encoded_Sec_WebSocket_Key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"))
```

另外兼容模式可以不实现，我测试后发现cloudflare的ws代理不会改`Sec-WebSocket-Key`

**Comment by krrr** [comment]
看样子你已经放弃了，我先关issue了，有需要欢迎再开
