### ISSUE TITLE
openshift.com

### ISSUE THREAD

**Issue by GlaucioAlmeida** [krrr/wstan#2]
It's working in the openshift.com?

**Comment by krrr** [comment]
Yes, see https://github.com/krrr/wstan#setup-for-openshift-v3
as far as i know v2 has been shut down

**Comment by GlaucioAlmeida** [comment]
This [link to docker](https://cloud.docker.com/app/krrr/repository/docker/krrr/wstan/general) is returning a error 500 :(

**Comment by krrr** [comment]
it's a mistake, i have fixed the link: https://hub.docker.com/r/krrr/wstan/

**Comment by GlaucioAlmeida** [comment]
thanks!
