### ISSUE TITLE
我在服务器和本地机器mac上都安装了wstan,但具体怎么用？

### ISSUE THREAD

**Issue by luckypoem** [krrr/wstan#4]
两边都是pip3 install wstan,
不过具体怎么用呢？能具体说说吗？

**Comment by luckypoem** [comment]
TUN_ADDR怎么填？像10.6.0.1/24这样吗？

**Comment by luckypoem** [comment]
root@ar:~# wstan --gen-key
A fresh random key: 1FkhWM4lHztCvpCBbzUkGQ==
root@ar:~# wstan --tun-addr 10.6.0.1/24 --tun-port 2356
uri not specified

该怎么指定uri ？
root@ar:~#

**Comment by krrr** [comment]
https://github.com/krrr/wstan#setup
如果没域名就把yourserver.com换成你服务器的ip地址。端口用host:port形式

**Comment by luckypoem** [comment]
哦，现在搞定。
服务器端运行wstan ws://0.0.0.0:2356 1FkhWM4lHztCvpCBbzUkGQ== -s
客户机器mac上运行：wstan ws://my-vps-ip:2356 1FkhWM4lHztCvpCBbzUkGQ== -c

会显示：
wstan client -- SOCKS5/HTTP(S) server listening on localhost:1080

不过如何修改本地监听的端口？因为1080已被ss占用。

**Comment by krrr** [comment]
仔细看说明，--port选项。你的1080被占用了，但是watan没有报错退出对吗？

**Comment by luckypoem** [comment]
wstan ws://my-vps-ip:2356 1FkhWM4lHztCvpCBbzUkGQ== -c --port 1234

**Comment by luckypoem** [comment]
我发现你这个程序有个特点：本地机器跟北京时间的误差不能超过10秒，一超过10秒就不能翻墙。如何去掉这个特性，因为老是要去调整时间有点烦。
